### ISSUE TITLE
Task-1 submissions

### ISSUE THREAD

**Issue by phantom654** [GeekHaven/Codelines#1]

**Comment by Rahul171201** [comment]
@phantom654 can I take up this issue . Also kindly describe the issue more precisely

**Comment by phantom654** [comment]
@Rahul171201 This is a competitive coding repository. You will be given a problem(in problem_statement.md) and also it's solution(in solution.cpp) file. But there will be some errors in the solution. You have to identify those errors and correct the solution without changing the logic used in provided code(i.e. soution.cpp). A PR with the correct solution should be make addressing this issue(i.e Task-1 submissions #1).

Also regarding assigning this issue to you, can you please clarify if you are from IIIT Allahabad or not (I can't find your college name in your profile). This is a college event we are not entertaining any PRs outside the college domain due to shortage of issues :(

**Comment by shyamTayal** [comment]
I want to work on this one . Can i? I am from IIIT Allahabad IIB2019008

**Comment by phantom654** [comment]
@Rahul171201 @shyamTayal This repository is open for everyone and first 10 correct PR's will be merged.

**Comment by Tushargupta9800** [comment]
@phantom654 Can I work on this issue as well??

**Comment by utkarshgarg123** [comment]
I would like to work on this issue.

**Comment by phantom654** [comment]
@Tushargupta9800 @utkarshgarg123 This repository is open for everyone and first 10 correct PR's will be merged.

**Comment by DevilAJ** [comment]
I am willing to work on that issue.

**Comment by phantom654** [comment]
@Rahul171201 @utkarshgarg123 @shyamTayal @Tushargupta9800 @DevilAJ Problem statement has been changed slightly. In instruction 2 of Problem_statement, allowed absolute change in constants has been changed to 100 (earlier it was 10).

**Comment by Kalpana200** [comment]
I want to contribute in this issue .

**Comment by phantom654** [comment]
@utkarshgarg123 @shyamTayal @DevilAJ @Tushargupta9800 @Kalpana200 @Rahul171201 
As many days have passed and we have an almost correct PR, this issue will be closed today at 1.pm. After that no PR's will be merged.
